// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gate.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NULL struct {
}

func (m *NULL) Reset()                    { *m = NULL{} }
func (m *NULL) String() string            { return proto.CompactTextString(m) }
func (*NULL) ProtoMessage()               {}
func (*NULL) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// 登录
type LOGIN_REQ struct {
	Serverid int32  `protobuf:"varint,1,opt,name=serverid" json:"serverid,omitempty"`
	Uuid     string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	Account  string `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	Pwd      string `protobuf:"bytes,4,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *LOGIN_REQ) Reset()                    { *m = LOGIN_REQ{} }
func (m *LOGIN_REQ) String() string            { return proto.CompactTextString(m) }
func (*LOGIN_REQ) ProtoMessage()               {}
func (*LOGIN_REQ) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LOGIN_REQ) GetServerid() int32 {
	if m != nil {
		return m.Serverid
	}
	return 0
}

func (m *LOGIN_REQ) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *LOGIN_REQ) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LOGIN_REQ) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type LOGIN_ACK struct {
	Uid   int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Level int32  `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
}

func (m *LOGIN_ACK) Reset()                    { *m = LOGIN_ACK{} }
func (m *LOGIN_ACK) String() string            { return proto.CompactTextString(m) }
func (*LOGIN_ACK) ProtoMessage()               {}
func (*LOGIN_ACK) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *LOGIN_ACK) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LOGIN_ACK) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LOGIN_ACK) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

// 退出
type LOGOUT_REQ struct {
	Null *NULL `protobuf:"bytes,1,opt,name=null" json:"null,omitempty"`
}

func (m *LOGOUT_REQ) Reset()                    { *m = LOGOUT_REQ{} }
func (m *LOGOUT_REQ) String() string            { return proto.CompactTextString(m) }
func (*LOGOUT_REQ) ProtoMessage()               {}
func (*LOGOUT_REQ) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *LOGOUT_REQ) GetNull() *NULL {
	if m != nil {
		return m.Null
	}
	return nil
}

// 通用回复
type COMMON_ACK struct {
	Api PROTO `protobuf:"varint,1,opt,name=api,enum=protocol.PROTO" json:"api,omitempty"`
	Err ERR   `protobuf:"varint,2,opt,name=err,enum=protocol.ERR" json:"err,omitempty"`
}

func (m *COMMON_ACK) Reset()                    { *m = COMMON_ACK{} }
func (m *COMMON_ACK) String() string            { return proto.CompactTextString(m) }
func (*COMMON_ACK) ProtoMessage()               {}
func (*COMMON_ACK) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *COMMON_ACK) GetApi() PROTO {
	if m != nil {
		return m.Api
	}
	return PROTO_TEST_GATE
}

func (m *COMMON_ACK) GetErr() ERR {
	if m != nil {
		return m.Err
	}
	return ERR_OK
}

// 心跳包
type HEART_REQ struct {
	Null *NULL `protobuf:"bytes,1,opt,name=null" json:"null,omitempty"`
}

func (m *HEART_REQ) Reset()                    { *m = HEART_REQ{} }
func (m *HEART_REQ) String() string            { return proto.CompactTextString(m) }
func (*HEART_REQ) ProtoMessage()               {}
func (*HEART_REQ) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *HEART_REQ) GetNull() *NULL {
	if m != nil {
		return m.Null
	}
	return nil
}

// gate 通信测试协议
type TEST_GATE_REQ struct {
	Start int64 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
}

func (m *TEST_GATE_REQ) Reset()                    { *m = TEST_GATE_REQ{} }
func (m *TEST_GATE_REQ) String() string            { return proto.CompactTextString(m) }
func (*TEST_GATE_REQ) ProtoMessage()               {}
func (*TEST_GATE_REQ) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *TEST_GATE_REQ) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func init() {
	proto.RegisterType((*NULL)(nil), "protocol.NULL")
	proto.RegisterType((*LOGIN_REQ)(nil), "protocol.LOGIN_REQ")
	proto.RegisterType((*LOGIN_ACK)(nil), "protocol.LOGIN_ACK")
	proto.RegisterType((*LOGOUT_REQ)(nil), "protocol.LOGOUT_REQ")
	proto.RegisterType((*COMMON_ACK)(nil), "protocol.COMMON_ACK")
	proto.RegisterType((*HEART_REQ)(nil), "protocol.HEART_REQ")
	proto.RegisterType((*TEST_GATE_REQ)(nil), "protocol.TEST_GATE_REQ")
}

func init() { proto.RegisterFile("gate.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x41, 0x6f, 0xb2, 0x40,
	0x10, 0x8d, 0x1f, 0xe0, 0xa7, 0x63, 0xb4, 0xcd, 0xc6, 0x03, 0xf1, 0x52, 0xbb, 0x49, 0x13, 0x4f,
	0xb6, 0xa1, 0xbf, 0x80, 0x18, 0x42, 0x9b, 0xa2, 0x6b, 0xa7, 0x78, 0x36, 0x14, 0x36, 0x86, 0x84,
	0x02, 0x59, 0x16, 0xfb, 0xf7, 0x9b, 0x1d, 0xa4, 0x5e, 0x7b, 0xe2, 0xbd, 0x79, 0xbc, 0x37, 0x6f,
	0x16, 0xe0, 0x94, 0x68, 0xb9, 0xae, 0x55, 0xa5, 0x2b, 0x36, 0xa2, 0x4f, 0x5a, 0x15, 0x8b, 0x49,
	0x5a, 0x95, 0x8d, 0xee, 0xc6, 0x7c, 0x08, 0xf6, 0xee, 0x10, 0x45, 0xfc, 0x04, 0xe3, 0x48, 0x84,
	0xaf, 0xbb, 0x23, 0x06, 0xef, 0x6c, 0x01, 0xa3, 0x46, 0xaa, 0xb3, 0x54, 0x79, 0xe6, 0x0e, 0x96,
	0x83, 0x95, 0x83, 0xbf, 0x9c, 0x31, 0xb0, 0xdb, 0x36, 0xcf, 0xdc, 0x7f, 0xcb, 0xc1, 0x6a, 0x8c,
	0x84, 0x99, 0x0b, 0xff, 0x93, 0x34, 0xad, 0xda, 0x52, 0xbb, 0x16, 0x8d, 0x7b, 0xca, 0x6e, 0xc1,
	0xaa, 0xbf, 0x33, 0xd7, 0xa6, 0xa9, 0x81, 0x3c, 0xec, 0x17, 0xf9, 0x9b, 0x37, 0x23, 0xb7, 0x97,
	0x1d, 0x16, 0x1a, 0x68, 0xe2, 0xcb, 0xe4, 0x4b, 0xf6, 0xf1, 0x06, 0xb3, 0x39, 0x38, 0x85, 0x3c,
	0xcb, 0x82, 0xc2, 0x1d, 0xec, 0x08, 0x7f, 0x02, 0x88, 0x44, 0x28, 0x0e, 0x31, 0x55, 0xe6, 0x60,
	0x97, 0x6d, 0x51, 0x50, 0xd4, 0xc4, 0x9b, 0xad, 0xfb, 0x6b, 0xd7, 0xe6, 0x3a, 0x24, 0x8d, 0xef,
	0x01, 0x36, 0x62, 0xbb, 0x15, 0xdd, 0xee, 0x7b, 0xb0, 0x92, 0x3a, 0x27, 0xc3, 0xcc, 0xbb, 0xb9,
	0x1a, 0xf6, 0x28, 0x62, 0x81, 0x46, 0x63, 0x77, 0x60, 0x49, 0xa5, 0xa8, 0xcb, 0xcc, 0x9b, 0x5e,
	0x7f, 0x09, 0x10, 0xd1, 0x28, 0xfc, 0x11, 0xc6, 0x2f, 0x81, 0x8f, 0x7f, 0xaf, 0xf0, 0x00, 0xd3,
	0x38, 0xf8, 0x88, 0x8f, 0xa1, 0x1f, 0x07, 0x64, 0x9a, 0x83, 0xd3, 0xe8, 0x44, 0xe9, 0xcb, 0x1b,
	0x74, 0xe4, 0x73, 0x48, 0xde, 0xe7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x2b, 0xb0, 0x17,
	0xc1, 0x01, 0x00, 0x00,
}
